import localFont from "next/font/local";
import "./globals.css";
import DashNavbar from "./components/navbar/dashNavbar";
import 'bootstrap/dist/css/bootstrap.min.css';
import Sidebar from "./components/sidebar/sidebar";
import { Col, Container, Row } from "react-bootstrap";
import "./general.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Next | Abdo Store Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>        
        <DashNavbar />
        <Container className="p-0 m-0 !w-full !max-w-full">
          <Row>
            <Col sm={0} md={3} lg={'auto'} className="layoutSidebarCol hidden md:!flex">
            <Sidebar />
            </Col>
            <Col xs={12} md={9} lg={'auto'} className="layoutContentCol">
            {children}
            </Col>
          </Row>
        </Container>
      </body>
    </html>
  );
}
